export const placeCategories = [
  "home",
  "restaurant",
  "cafe",
  "bar",
  "nightclub",
  "beach",
  "park",
  "garden",
  "mountain",
  "forest",
  "hotel",
  "resort",
  "shopping_mall",
  "market",
  "supermarket",
  "cinema",
  "theater",
  "museum",
  "gallery",
  "stadium",
  "gym",
  "spa",
  "school",
  "university",
  "library",
  "office",
  "coworking_space",
  "hospital",
  "pharmacy",
  "bank",
  "church",
  "mosque",
  "temple",
  "airport",
  "bus_station",
  "train_station",
  "gas_station",
  "parking_lot",
  "tourist_attraction",
  "landmark"
] as const;

export type PlaceCategory = typeof placeCategories[number];
